name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        arduino-platform: ["esp32:esp32"]

        include:
          - arduino-platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@master

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip pyserial

      - name: Install Platform
        run: |
          arduino-cli core update-index --verbose
          arduino-cli core install ${{ matrix.arduino-platform }} --verbose

      - name: Install Libraries
        run: |
          arduino-cli lib update-index --verbose
          arduino-cli lib install NTPClient FastLED ArduinoJson --verbose
          git clone https://github.com/256dpi/arduino-mqtt.git ~/Arduino/libraries/arduino-mqtt
          git clone https://github.com/Seeed-Studio/Seeed_VEML6070.git ~/Arduino/libraries/Seeed_VEML6070
          git clone https://github.com/Seeed-Studio/Grove_BME280.git ~/Arduino/libraries/Grove_BME280
          git clone https://github.com/NCAR/esp32-atomlite-arduino-iotwx.git ~/Arduino/libraries/esp32-atomlite-arduino-iotwx

      - name: List Installed Libraries
        run: |
          ls -lah ~/Arduino/libraries/*

      - name: Compile sketch
        run: |
          arduino-cli compile --fqbn ${{ matrix.fqbn }}:PartitionScheme=huge_app,UploadSpeed=115200 \
             esp32-atomlite-arduino-atmos-node.ino --verbose
